<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\FiscalHub.Application\FiscalHub.Application.csproj" />
    <ProjectReference Include="..\..\..\FiscalHub.Domain\FiscalHub.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.1" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FiscalHub.Adapters.Inbound.Xml.Tests" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
